FROM node:18-alpine as builder
WORKDIR /app
COPY next/package*.json ./
RUN npm install
COPY next/ ./
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
CMD ["npm", "start"]
