version: '3.8'

services:
  frontend:
    container_name: frontend-next-dev
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - hackathon-demo-net

networks:
  hackathon-demo-net:
