services:
  frontend:
    container_name: frontend-next-dev
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/next:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API-KEY=MTgpZPAnSnxxqZzFGVfj44aF-MwFes8LG4xv9Ubp
    networks:
      - hackathon-demo-net

  backend:
    container_name: backend-rust-dev
    build:
      context: ./backend
    command: cargo run
    volumes:
      - ./backend/rust:/app
    networks:
      - hackathon-demo-net
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://hackathon_demo_admin:hackathon_demo@db:3306/hackathon_demo_db
      - API-KEY=MTgpZPAnSnxxqZzFGVfj44aF-MwFes8LG4xv9Ubp

  nginx:
    container_name: nginx-proxy
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - hackathon-demo-net

  db:
    container_name: mysql-db
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: hackathon_demo
      MYSQL_DATABASE: hackathon_demo_db
      MYSQL_USER: hackathon_demo_admin
      MYSQL_PASSWORD: hackathon_demo
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon-demo-net
  
  migrator:
    container_name: sqlx-migrator
    build:
      context: ./migrator
    volumes:
      - ./migrator/migrations:/app/migrations
      - ./migrator/sqlx.toml:/app/sqlx.toml
    environment:
      - DATABASE_URL=mysql://hackathon_demo_admin:hackathon_demo@db:3306/hackathon_demo_db
    depends_on:
      - db
    networks:
      - hackathon-demo-net

volumes:
  db_data:

networks:
  hackathon-demo-net:
